receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - 'http://localhost:3000'
            - 'http://localhost:1234'

processors:
  batch:

exporters:
  file:
    path: /var/lib/data.json
  debug:
    verbosity: detailed
  logging:
    verbosity: detailed
  # otlp:
  #   endpoint: 'api.honeycomb.io:443'
  #   headers:
  #     'x-honeycomb-team': 'your-key-here'

service:
  telemetry:
    logs:
      level: DEBUG
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [file, debug]
