FROM node:18-bullseye

# Create app directory
WORKDIR /usr/src/app

COPY . .

RUN npm install

RUN npm run build

WORKDIR /usr/src/app/examples/custom-with-collector-ts

RUN npm install
RUN npm run build


EXPOSE 1234
CMD [ "npm", "start" ]
